- name: Instalando puppet agent
  package:
   name: puppet-agent
   state: present
   update_cache: yes

- name: Instalando puppet server - Debian
  package:
   name: puppetserver
   state: present
   update_cache: yes
  when: ansible_hostname == "devops"
