---
# tasks file for container-docker
#
- name: Criar pasta volume
  file:
   name: "{{item}}"
   state: directory
  with_items:
   - blue
   - green

- name: criando os containers
  docker_container:
   name: "{{item.name}}"
   image: httpd
   state: started
   volumes:
    - "{{item.volume}}:/usr/local/apache2/htdocs/"
  with_items:
   - {name: blue, volume: /blue}
   - {name: green, volume: /green}
