- name: Adicionando os usuarios
  user:
   name: "{{item.name}}"
   state: present
   shell: '/bin/bash'
   home: "{{item.home}}"
   password: '$1$zEYeWc54$WRzmHK08MOL0ojsGeYWqQ/'
  with_items:
   - { name: devops, home: /srv/devops }
   - { name: developer, home: /srv/developer }
   - { name: marcosjustino, home: /srv/marcosjustino }
