- name: Criando o cenario de micro servicoes
  hosts: docker
  tasks:
   - name: Criar pasta volume
     file: 
      path: /laboratorio
      state: directory
          
   - name: criando os containers
     docker_container:
      name: "{{ item }}"
      image: httpd
      state: started
      volumes:
       - /laboratorio:/usr/local/apache2/htdocs
     with_items:
      - laboratorio_blue
      - laboratorio_green
