---
- name: Utilizando condicao
  hosts: all
  vars:
   - databasename: frodo
   - databasepassword: 4linux
   - databasehost: postgres.dexter.com.br
  tasks: 
   - name: Instalando apache
     package:
      name: apache2
     when: ansible_os_family == "Debian"

   - name: Instalando apache
     package:
      name: httpd
     when: ansible_os_family == "RedHat"

   - name: Copiando um arquivo template
     template:
      src: wp-config
      dest: /var/www/html
